# MantraSetu AI Backend - Safe Cleanup Script Phase 1
# Generated by Enterprise Runtime Dependency Audit
# Risk Level: ZERO (Batch 1 - Safe To Delete Files Only)

Write-Host "Starting MantraSetu Safe Cleanup - Phase 1..." -ForegroundColor Cyan

$filesToDelete = @(
    "app\ai\intent\intent_types.py",
    "app\api\dependencies.py",
    "app\services\browser\automation_engine_service.py",
    "app\services\browser\browser_executor_service.py",
    "app\services\browser\command_resolver_service.py",
    "app\services\browser\session_manager_service.py",
    "app\services\browser\target_resolver_service.py",
    "app\services\browser_intelligence\dom_intelligence_service.py",
    "app\services\browser_intelligence\navigation_graph_service.py",
    "app\services\browser_intelligence\page_context_service.py",
    "app\services\browser_intelligence\task_context_service.py",
    "app\services\execution\execution_pipeline_service.py",
    "app\services\execution\execution_runner_service.py",
    "app\services\execution\workflow_planner_service.py",
    "app\services\tools\tool_registry_service.py",
    "scripts\run_production_health_check.py"
)

$deletedCount = 0

foreach ($file in $filesToDelete) {
    if (Test-Path $file) {
        Remove-Item -Path $file -Force
        Write-Host "Successfully deleted: $file" -ForegroundColor Green
        $deletedCount++
    } else {
        Write-Host "File not found (already removed or moved): $file" -ForegroundColor Yellow
    }
}

Write-Host "`nPhase 1 Cleanup Complete. $deletedCount files removed." -ForegroundColor Green
